/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import controlador.AlumnoDAO;
import controlador.*;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import modelo.*;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Laboratorio
 */
public class CrudContrato extends javax.swing.JFrame {
     private ContratoDAO objContrato = new ContratoDAO();

    /**
     * Creates new form CrudContrato
     */
    public CrudContrato() {
        initComponents();
        jButtonEliminarContrato.setEnabled(false);
        jButtonModificarContrato.setEnabled(false);

        SpinnerNumberModel modelo = new SpinnerNumberModel();
        modelo.setMinimum(18);
        modelo.setMaximum(100);
        jSpinnerEdadContrato.setModel(modelo);
        jSpinnerEdadContrato.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarContrato = new javax.swing.JButton();
        jButtonBuscarContrato = new javax.swing.JButton();
        jButtonVolverContrato = new javax.swing.JButton();
        jButtonEliminarContrato = new javax.swing.JButton();
        jButtonModificarContrato = new javax.swing.JButton();
        jButtonLimpiarContrato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreContrato = new javax.swing.JTextField();
        jTextFieldRutContrato = new javax.swing.JTextField();
        jTextFieldNotasContrato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreApoderadoContrato = new javax.swing.JTextField();
        jSpinnerEdadContrato = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAgregarContrato.setText("Agregar");
        jButtonAgregarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarContratoActionPerformed(evt);
            }
        });

        jButtonBuscarContrato.setText("Buscar");
        jButtonBuscarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarContratoActionPerformed(evt);
            }
        });

        jButtonVolverContrato.setText("Volver");
        jButtonVolverContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverContratoActionPerformed(evt);
            }
        });

        jButtonEliminarContrato.setText("Eliminar");
        jButtonEliminarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarContratoActionPerformed(evt);
            }
        });

        jButtonModificarContrato.setText("Modificar");
        jButtonModificarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarContratoActionPerformed(evt);
            }
        });

        jButtonLimpiarContrato.setText("Limpiar");
        jButtonLimpiarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarContratoActionPerformed(evt);
            }
        });

        jLabel1.setText("nombre:");

        jLabel2.setText("rut:");

        jLabel3.setText("notas:");

        jTextFieldNombreContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreContratoActionPerformed(evt);
            }
        });

        jLabel4.setText("nombre apoderado:");

        jTextFieldNombreApoderadoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApoderadoContratoActionPerformed(evt);
            }
        });

        jSpinnerEdadContrato.setToolTipText("La edad debe ser mayor a 18");

        jLabel5.setText("Edad postulante:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("MANTENEDOR CONTRATOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSpinnerEdadContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNombreApoderadoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel2)
                                    .addGap(54, 54, 54)
                                    .addComponent(jTextFieldRutContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNotasContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombreContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAgregarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBuscarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonModificarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEliminarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLimpiarContrato)
                                .addGap(72, 72, 72)
                                .addComponent(jButtonVolverContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel6)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldRutContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombreContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNotasContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNombreApoderadoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAgregarContrato)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarContrato)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarContrato)
                                .addGap(9, 9, 9)
                                .addComponent(jButtonModificarContrato)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonLimpiarContrato)
                                .addComponent(jButtonVolverContrato)))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerEdadContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarContratoActionPerformed
        // TODO add your handling code here:

        try {
            String rut = jTextFieldRutContrato.getText();
            String nombre = jTextFieldNombreContrato.getText();
            String notas = jTextFieldNotasContrato.getText();
            String nombreApoderado = jTextFieldNombreApoderadoContrato.getText();
            byte edad = Byte.parseByte(jSpinnerEdadContrato.getValue().toString());

            if (!rut.equals("") && !nombre.equals("") && !notas.equals("") && !nombreApoderado.equals("") && edad >= 0) {
                
                Contrato x = new Contrato(rut, nombre, notas, nombreApoderado, edad);
                //String rut, String nombre, int edad, String genero, String email, String carrera

                if (objContrato.agregar(x) == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Bien, datos grabados");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error, rut ya existe");
                }
            }else {
                JOptionPane.showMessageDialog(rootPane, "Error, los campos NO deben estar vacios");
            }

            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error, edad debe ser un número");
        }
    }//GEN-LAST:event_jButtonAgregarContratoActionPerformed

    private void jButtonBuscarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarContratoActionPerformed
        // TODO add your handling code here:
        Contrato contrato = null;
        String rut = jTextFieldRutContrato.getText();
        jTextFieldRutContrato.setEnabled(false);

        if (!rut.equals("")) {
            contrato = objContrato.Buscar(rut);
            if (contrato != null && contrato instanceof Contrato) {
                jTextFieldRutContrato.setText(contrato.getRut());
                jTextFieldNombreContrato.setText(contrato.getNombre());
                jTextFieldNotasContrato.setText(contrato.getNotas());
                jTextFieldNombreApoderadoContrato.setText(contrato.getNombreApoderado());
                jSpinnerEdadContrato.setValue(contrato.getEdad());

                jButtonEliminarContrato.setEnabled(true);
                jButtonModificarContrato.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Error, el rut ingresado es incorrecto");
            }
        }
    }//GEN-LAST:event_jButtonBuscarContratoActionPerformed

    private void jButtonVolverContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverContratoActionPerformed
        // TODO add your handling code here:
        this.dispose();// cerrar solamente esta ventana, NO todas
    }//GEN-LAST:event_jButtonVolverContratoActionPerformed

    private void jButtonEliminarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarContratoActionPerformed
        // TODO add your handling code here:

        try {
            String rut = jTextFieldRutContrato.getText();
            if (!rut.equals("")) {
                int n = JOptionPane.showConfirmDialog(null, "¿Esta seguro  que desea eliminar esta persona?",
                        "Confirmar", 0);

                if (n == 0) {
                    if (objContrato.Eliminar(rut) == true) {
                        int a = JOptionPane.OK_OPTION;
                        JOptionPane.showMessageDialog(this, "Contrato eliminada", "realizado", a);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "El rut no existe");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Eliminacion cancelada");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "El rut no tiene que estar en blanco");
            }
            limpiar();
        } catch (Exception ev) {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error");
        }

        //        try {
        //
        //            if (jTextFieldRut.isEnabled() == false) {
        //                String rut = jTextFieldRut.getText();
        //
        //                if (ContratoDAO.eliminar(rut) == true) {
        //                    JOptionPane.showMessageDialog(rootPane, "Bien,rut eliminado...");
        //                } else {
        //                    JOptionPane.showMessageDialog(rootPane, "Error,rut no existe...");
        //                }
        //                limpiar();
        //            }
        //        } catch (Exception ev) {
        //            JOptionPane.showMessageDialog(rootPane, "Error,rut no debe estar en blanco...");
        //        }
    }//GEN-LAST:event_jButtonEliminarContratoActionPerformed

    private void jButtonModificarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarContratoActionPerformed
        // TODO add your handling code here:
        jTextFieldRutContrato.setEnabled(false);
        try {
            String rut = jTextFieldRutContrato.getText();
            String nombre = jTextFieldNombreContrato.getText();
            String notas = jTextFieldNotasContrato.getText();
            String nombreApoderado = jTextFieldNombreApoderadoContrato.getText();
            byte edad = Byte.parseByte(jSpinnerEdadContrato.getValue().toString());
            
            if (!rut.equals("") && !nombre.equals("")  && !notas.equals("")&& !nombreApoderado.equals("") && edad >= 0) {

                Contrato x = new Contrato(rut, nombre, notas , nombreApoderado ,edad);
                //String rut, String nombre, int edad, String genero, String email, String carrera

                if (objContrato.modificar(x) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Bien, datos modificados");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error, rut ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error, los campos NO deben estar vacios");
            }

            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error, edad debe ser un número");
        }
    }//GEN-LAST:event_jButtonModificarContratoActionPerformed

    private void jButtonLimpiarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarContratoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarContratoActionPerformed
    public void limpiar() {
        jTextFieldRutContrato.setEnabled(true);
        jTextFieldRutContrato.setText("");
        jTextFieldNombreContrato.setText("");
        jTextFieldNotasContrato.setText("");
        jTextFieldNombreApoderadoContrato.setText("");
        jButtonEliminarContrato.setEnabled(false);
        jButtonModificarContrato.setEnabled(false);
        jSpinnerEdadContrato.setValue(18);
    }
    private void jTextFieldNombreContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreContratoActionPerformed

    private void jTextFieldNombreApoderadoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApoderadoContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreApoderadoContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarContrato;
    private javax.swing.JButton jButtonBuscarContrato;
    private javax.swing.JButton jButtonEliminarContrato;
    private javax.swing.JButton jButtonLimpiarContrato;
    private javax.swing.JButton jButtonModificarContrato;
    private javax.swing.JButton jButtonVolverContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinnerEdadContrato;
    private javax.swing.JTextField jTextFieldNombreApoderadoContrato;
    private javax.swing.JTextField jTextFieldNombreContrato;
    private javax.swing.JTextField jTextFieldNotasContrato;
    private javax.swing.JTextField jTextFieldRutContrato;
    // End of variables declaration//GEN-END:variables
}
