/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.GeneroDAO;
import controlador.*;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import modelo.*;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Laboratorio
 */
public class CrudGeneros extends javax.swing.JFrame {

    /**
     * Creates new form CrudGeneros
     */
    public CrudGeneros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextIdGenero = new javax.swing.JTextField();
        jButtonAgregarGeneros = new javax.swing.JButton();
        jButtonBuscarGeneros = new javax.swing.JButton();
        jButtonVolverGeneros = new javax.swing.JButton();
        jButtonEliminarGeneros = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonGeneros = new javax.swing.JButton();
        jComboBoxGeneroxd = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MANTENEDOR DE GENEROS");

        jLabel2.setText("Id:");

        jLabel3.setText("Genero:");

        jButtonAgregarGeneros.setText("Agregar");
        jButtonAgregarGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarGenerosActionPerformed(evt);
            }
        });

        jButtonBuscarGeneros.setText("Buscar");
        jButtonBuscarGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarGenerosActionPerformed(evt);
            }
        });

        jButtonVolverGeneros.setText("Volver");
        jButtonVolverGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverGenerosActionPerformed(evt);
            }
        });

        jButtonEliminarGeneros.setText("Eliminar");
        jButtonEliminarGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarGenerosActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonGeneros.setText("Limpiar");
        jButtonGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerosActionPerformed(evt);
            }
        });

        jComboBoxGeneroxd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino", "No binario", "etc" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addComponent(jTextIdGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxGeneroxd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregarGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEliminarGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGeneros)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonVolverGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextIdGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxGeneroxd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAgregarGeneros)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarGeneros)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarGeneros)
                                .addGap(21, 21, 21)
                                .addComponent(jButtonModificar)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonGeneros)
                                .addComponent(jButtonVolverGeneros)))))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarGenerosActionPerformed
        // TODO add your handling code here:

        try {
            int id = Integer.valueOf(jTextIdGenero.getText());
            String nombreCarrera = jComboBoxGeneroxd.getSelectedItem().toString();
            if (id >=0 && !nombreCarrera.equals("")) {

                Genero x = new Genero(id, nombreCarrera);
                //String id, String genero, int edad, String genero, String email, String carrera

                if (GeneroDAO.agregar(x) == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Bien, datos grabados");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error, id ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error, los campos NO deben estar vacios");
            }

            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error, edad debe ser un número");
        }
    }//GEN-LAST:event_jButtonAgregarGenerosActionPerformed

    private void jButtonBuscarGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarGenerosActionPerformed
        // TODO add your handling code here:
        Genero genero = null;
        int id = Integer.valueOf(jTextIdGenero.getText());
        jTextIdGenero.setEnabled(false);
        jTextIdGenero.setEnabled(true);

        if (id >=0) {
            genero = GeneroDAO.buscar(String.valueOf(id));
            if (genero != null && genero instanceof Genero) {
                
                jTextIdGenero.setText(String.valueOf(id));
                jComboBoxGeneroxd.setSelectedItem(genero.getGenero());

                jButtonEliminarGeneros.setEnabled(true);
                jButtonModificar.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Error, id no debe estar en blanco");
            }
        }
    }//GEN-LAST:event_jButtonBuscarGenerosActionPerformed

    private void jButtonVolverGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverGenerosActionPerformed
        // TODO add your handling code here:
        this.dispose();// cerrar solamente esta ventana, NO todas
    }//GEN-LAST:event_jButtonVolverGenerosActionPerformed

    private void jButtonEliminarGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarGenerosActionPerformed
        // TODO add your handling code here:

        try {
            int id = Integer.parseInt(jTextIdGenero.getText());
            if (id>= 0) {
                int n = JOptionPane.showConfirmDialog(null, "¿Esta seguro  que desea eliminar esta persona?",
                    "Confirmar", 0);

                if (n == 0) {
                    if (GeneroDAO.eliminar(String.valueOf(id)) == true) {
                        JOptionPane.showMessageDialog(rootPane, "Genero eliminada");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "El id no existe");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Eliminacion cancelada");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "El id no tiene que estar en blanco");
            }
            limpiar();
        } catch (Exception ev) {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error");
        }

        //        try {
            //
            //            if (jTextFieldRut.isEnabled() == false) {
                //                String id = jTextFieldRut.getText();
                //
                //                if (GeneroDAO.eliminar(id) == true) {
                    //                    JOptionPane.showMessageDialog(rootPane, "Bien,id eliminado...");
                    //                } else {
                    //                    JOptionPane.showMessageDialog(rootPane, "Error,id no existe...");
                    //                }
                //                limpiar();
                //            }
            //        } catch (Exception ev) {
            //            JOptionPane.showMessageDialog(rootPane, "Error,id no debe estar en blanco...");
            //        }

    }//GEN-LAST:event_jButtonEliminarGenerosActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        jTextIdGenero.setEnabled(false);
        try {
            int id = Integer.valueOf(jTextIdGenero.getText());
            String genero = jComboBoxGeneroxd.getSelectedItem().toString();


            if (id >= 0 && !genero.equals("")) {

                Genero x = new Genero(id, genero);
                //String id, String genero, int edad, String genero, String email, String carrera

                if (GeneroDAO.modificar(x) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Bien, datos modificados");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error, id ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error, los campos NO deben estar vacios");
            }

            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error, edad debe ser un número");
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerosActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButtonGenerosActionPerformed
    public void limpiar() {
        jTextIdGenero.setText("");
        jComboBoxGeneroxd.setSelectedIndex(0);


    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudGeneros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarGeneros;
    private javax.swing.JButton jButtonBuscarGeneros;
    private javax.swing.JButton jButtonEliminarGeneros;
    private javax.swing.JButton jButtonGeneros;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolverGeneros;
    private javax.swing.JComboBox<String> jComboBoxGeneroxd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextIdGenero;
    // End of variables declaration//GEN-END:variables
}
